// Estoque de veículos — edite este arquivo para adicionar, alterar ou remover anúncios.
// Campos: id, tipo (carro|moto|caminhao|utilitario|onibus|carreta|trator), marca, modelo,
// versao, ano, km (ou horas, para tratores/máquinas), preco (R$), combustivel, cambio, cor,
// portas (opcional), destaque (true = aparece na home), descricao, opcionais (lista),
// cores do card (g1/g2) e icone (carro|sedan|suv|picape|moto|caminhao|van|onibus|carreta|trator).

const VEICULOS = [
  {
    id: 1,
    tipo: "carro",
    marca: "Chevrolet",
    modelo: "Onix",
    versao: "1.0 Turbo LTZ",
    ano: 2023,
    km: 28500,
    preco: 84900,
    combustivel: "Flex",
    cambio: "Automático",
    cor: "Branco",
    portas: 4,
    destaque: true,
    descricao:
      "Chevrolet Onix LTZ turbo, único dono, todas as revisões feitas em concessionária. Carro impecável, pneus novos e IPVA pago.",
    opcionais: [
      "Ar-condicionado digital",
      "Central multimídia MyLink",
      "Câmera de ré",
      "Sensor de estacionamento",
      "Controle de tração e estabilidade",
      "6 airbags",
    ],
    g1: "#1f6feb",
    g2: "#0d3b8f",
    icone: "carro",
  },
  {
    id: 2,
    tipo: "carro",
    marca: "Volkswagen",
    modelo: "T-Cross",
    versao: "1.4 TSI Highline",
    ano: 2022,
    km: 41200,
    preco: 129900,
    combustivel: "Flex",
    cambio: "Automático",
    cor: "Cinza",
    portas: 4,
    destaque: true,
    descricao:
      "T-Cross Highline completo, teto solar, rodas de liga leve 17\". SUV mais vendido da categoria, revisado e com garantia.",
    opcionais: [
      "Teto solar panorâmico",
      "ACC (piloto automático adaptativo)",
      "Painel digital Active Info Display",
      "Keyless com partida por botão",
      "Faróis full LED",
      "Bancos em couro",
    ],
    g1: "#57606a",
    g2: "#22272e",
    icone: "suv",
  },
  {
    id: 3,
    tipo: "carro",
    marca: "Fiat",
    modelo: "Strada",
    versao: "1.3 Freedom CD",
    ano: 2024,
    km: 12000,
    preco: 104900,
    combustivel: "Flex",
    cambio: "Manual",
    cor: "Vermelho",
    portas: 4,
    destaque: true,
    descricao:
      "Picape líder de vendas no Brasil. Strada cabine dupla, ideal para trabalho e lazer. Estado de zero km.",
    opcionais: [
      "Cabine dupla",
      "Central multimídia 7\"",
      "Protetor de caçamba",
      "Faróis de neblina",
      "Direção elétrica",
      "Vidros e travas elétricas",
    ],
    g1: "#c93c37",
    g2: "#7a1f1c",
    icone: "picape",
  },
  {
    id: 4,
    tipo: "carro",
    marca: "Toyota",
    modelo: "Corolla",
    versao: "2.0 XEi",
    ano: 2021,
    km: 55300,
    preco: 132900,
    combustivel: "Flex",
    cambio: "Automático CVT",
    cor: "Prata",
    portas: 4,
    destaque: false,
    descricao:
      "Toyota Corolla XEi, o sedã mais confiável do mercado. Manual, chave reserva e histórico completo de revisões.",
    opcionais: [
      "Toyota Safety Sense",
      "Bancos em couro",
      "Central multimídia com Android Auto/CarPlay",
      "Ar digital dual zone",
      "Piloto automático adaptativo",
    ],
    g1: "#8b949e",
    g2: "#3d444d",
    icone: "sedan",
  },
  {
    id: 5,
    tipo: "carro",
    marca: "Hyundai",
    modelo: "HB20",
    versao: "1.0 Sense",
    ano: 2022,
    km: 38900,
    preco: 64900,
    combustivel: "Flex",
    cambio: "Manual",
    cor: "Azul",
    portas: 4,
    destaque: false,
    descricao:
      "HB20 Sense econômico e completo, perfeito para o dia a dia e apps de mobilidade. Baixo custo de manutenção.",
    opcionais: [
      "Ar-condicionado",
      "Direção elétrica",
      "Vidros elétricos",
      "Travas elétricas",
      "Airbags frontais",
      "Freios ABS",
    ],
    g1: "#316dca",
    g2: "#12315f",
    icone: "carro",
  },
  {
    id: 6,
    tipo: "carro",
    marca: "Jeep",
    modelo: "Compass",
    versao: "1.3 T270 Longitude",
    ano: 2023,
    km: 22100,
    preco: 154900,
    combustivel: "Flex",
    cambio: "Automático",
    cor: "Preto",
    portas: 4,
    destaque: true,
    descricao:
      "Jeep Compass Longitude turbo flex, SUV médio referência em conforto e tecnologia. Único dono, sem detalhes.",
    opcionais: [
      "Central multimídia 10.1\"",
      "Painel de instrumentos digital 10.25\"",
      "Frenagem autônoma de emergência",
      "Alerta de ponto cego",
      "Carregador de celular por indução",
      "Rodas 18\"",
    ],
    g1: "#2d333b",
    g2: "#0d1117",
    icone: "suv",
  },
  {
    id: 7,
    tipo: "moto",
    marca: "Honda",
    modelo: "CB 500F",
    versao: "ABS",
    ano: 2023,
    km: 8700,
    preco: 39900,
    combustivel: "Gasolina",
    cambio: "Manual 6 marchas",
    cor: "Vermelho",
    destaque: true,
    descricao:
      "Honda CB 500F com ABS, baixa quilometragem, pneus meia-vida e escapamento original. Moto de garagem, sem quedas.",
    opcionais: [
      "Freios ABS nas duas rodas",
      "Painel full digital LCD",
      "Iluminação full LED",
      "Slipper clutch (embreagem deslizante)",
    ],
    g1: "#c93c37",
    g2: "#5d1a17",
    icone: "moto",
  },
  {
    id: 8,
    tipo: "moto",
    marca: "Yamaha",
    modelo: "MT-03",
    versao: "321cc ABS",
    ano: 2022,
    km: 15400,
    preco: 27900,
    combustivel: "Gasolina",
    cambio: "Manual 6 marchas",
    cor: "Azul",
    destaque: false,
    descricao:
      "Yamaha MT-03, naked ágil e econômica, ideal para cidade e estrada. Revisões em dia e documentação ok.",
    opcionais: [
      "Freios ABS",
      "Painel digital",
      "Farol full LED",
      "Chassi Diamond leve",
    ],
    g1: "#316dca",
    g2: "#101a45",
    icone: "moto",
  },
  {
    id: 9,
    tipo: "moto",
    marca: "Honda",
    modelo: "Biz 125",
    versao: "ES",
    ano: 2024,
    km: 3200,
    preco: 15900,
    combustivel: "Flex",
    cambio: "Semi-automático",
    cor: "Branco",
    destaque: false,
    descricao:
      "Honda Biz 125 praticamente zero, ideal para trabalho e entregas. Partida elétrica, baú incluso na negociação.",
    opcionais: [
      "Partida elétrica",
      "Porta-objetos sob o assento",
      "Freio CBS combinado",
      "Painel com indicador de marcha",
    ],
    g1: "#8b949e",
    g2: "#44494f",
    icone: "moto",
  },
  {
    id: 10,
    tipo: "caminhao",
    marca: "Mercedes-Benz",
    modelo: "Accelo 815",
    versao: "Baú 4x2",
    ano: 2020,
    km: 185000,
    preco: 219900,
    combustivel: "Diesel",
    cambio: "Manual",
    cor: "Branco",
    destaque: true,
    descricao:
      "Mercedes-Benz Accelo 815 com baú, pronto para trabalhar. Motor revisado, pneus em bom estado, documentação em dia.",
    opcionais: [
      "Baú de alumínio 5,5m",
      "Ar-condicionado",
      "Direção hidráulica",
      "Tacógrafo digital",
      "Vidros elétricos",
    ],
    g1: "#57606a",
    g2: "#1c2128",
    icone: "caminhao",
  },
  {
    id: 11,
    tipo: "caminhao",
    marca: "Volkswagen",
    modelo: "Delivery 11.180",
    versao: "Chassi 4x2",
    ano: 2021,
    km: 142000,
    preco: 249900,
    combustivel: "Diesel",
    cambio: "Manual",
    cor: "Prata",
    destaque: false,
    descricao:
      "VW Delivery 11.180 no chassi, aceita implemento. Caminhão forte e econômico, ideal para distribuição urbana.",
    opcionais: [
      "Ar-condicionado",
      "Direção hidráulica",
      "Computador de bordo",
      "Freios a ar com ABS",
    ],
    g1: "#8b949e",
    g2: "#30363d",
    icone: "caminhao",
  },
  {
    id: 12,
    tipo: "utilitario",
    marca: "Fiat",
    modelo: "Fiorino",
    versao: "1.4 Endurance",
    ano: 2023,
    km: 31000,
    preco: 92900,
    combustivel: "Flex",
    cambio: "Manual",
    cor: "Branco",
    destaque: false,
    descricao:
      "Fiat Fiorino Endurance, furgão compacto ideal para entregas na cidade. Grande capacidade de carga e economia.",
    opcionais: [
      "Ar-condicionado",
      "Direção hidráulica",
      "Divisória de carga",
      "Porta lateral corrediça",
      "Capacidade de 650 kg",
    ],
    g1: "#8b949e",
    g2: "#44494f",
    icone: "van",
  },
  {
    id: 13,
    tipo: "utilitario",
    marca: "Renault",
    modelo: "Master",
    versao: "2.3 dCi Furgão L2H2",
    ano: 2022,
    km: 68000,
    preco: 189900,
    combustivel: "Diesel",
    cambio: "Manual",
    cor: "Branco",
    destaque: false,
    descricao:
      "Renault Master furgão teto alto, revisada, ideal para logística, mudanças ou transformação em motorhome.",
    opcionais: [
      "Ar-condicionado",
      "Direção elétrica",
      "Porta lateral corrediça",
      "13 m³ de capacidade",
      "Sensor de ré",
    ],
    g1: "#8b949e",
    g2: "#3d444d",
    icone: "van",
  },
  {
    id: 14,
    tipo: "carro",
    marca: "Ford",
    modelo: "Ranger",
    versao: "3.0 V6 Limited 4x4",
    ano: 2024,
    km: 9800,
    preco: 319900,
    combustivel: "Diesel",
    cambio: "Automático 10 marchas",
    cor: "Azul",
    portas: 4,
    destaque: true,
    descricao:
      "Nova Ranger Limited V6, topo de linha, praticamente zero km. Picape com o melhor pacote tecnológico da categoria.",
    opcionais: [
      "Motor V6 turbodiesel 250 cv",
      "Tração 4x4 com reduzida",
      "Central multimídia vertical 12\"",
      "Bancos em couro com ajuste elétrico",
      "Piloto automático adaptativo",
      "Capota marítima",
    ],
    g1: "#1f6feb",
    g2: "#0a2a66",
    icone: "picape",
  },
  {
    id: 15,
    tipo: "onibus",
    marca: "Volare",
    modelo: "W9 Fly",
    versao: "Executivo 28 lugares",
    ano: 2019,
    km: 198000,
    preco: 329900,
    combustivel: "Diesel",
    cambio: "Manual",
    cor: "Branco",
    destaque: true,
    descricao:
      "Micro-ônibus Volare W9 Fly Executivo com 28 lugares, ar-condicionado e poltronas reclináveis. Ideal para fretamento, turismo e transporte de funcionários. Revisado e com documentação em dia.",
    opcionais: [
      "Ar-condicionado",
      "28 poltronas executivas reclináveis",
      "Bagageiro externo",
      "Porta-pacotes interno",
      "Tacógrafo digital",
      "Câmera de ré",
    ],
    g1: "#316dca",
    g2: "#12315f",
    icone: "onibus",
  },
  {
    id: 16,
    tipo: "carreta",
    marca: "Randon",
    modelo: "SR Graneleira",
    versao: "3 eixos",
    ano: 2020,
    km: null,
    preco: 149900,
    combustivel: "—",
    cambio: "—",
    cor: "Cinza",
    destaque: false,
    descricao:
      "Semirreboque Randon graneleiro 3 eixos, assoalho e grades revisados, pneus em bom estado. Pronto para engatar e trabalhar no transporte de grãos e cargas secas.",
    opcionais: [
      "3 eixos com suspensão mecânica",
      "Grades graneleiras completas",
      "Lonas de cobertura",
      "Pneus em bom estado",
      "Documentação em dia",
    ],
    g1: "#57606a",
    g2: "#22272e",
    icone: "carreta",
  },
  {
    id: 17,
    tipo: "trator",
    marca: "John Deere",
    modelo: "6110J",
    versao: "4x4 Cabinado",
    ano: 2021,
    km: null,
    horas: 1850,
    preco: 385000,
    combustivel: "Diesel",
    cambio: "PowrQuad 16x16",
    cor: "Verde",
    destaque: true,
    descricao:
      "Trator John Deere 6110J 4x4 cabinado com apenas 1.850 horas de uso. Máquina de único dono, revisada em concessionária, pneus com ótimo estado. Pronto para o trabalho no campo.",
    opcionais: [
      "Cabine com ar-condicionado",
      "Tração 4x4",
      "Transmissão PowrQuad 16x16",
      "Levante hidráulico de 3 pontos",
      "Contrapesos dianteiros",
      "Piloto hidráulico",
    ],
    g1: "#2f7d32",
    g2: "#123f14",
    icone: "trator",
  },
];

// Configurações gerais da loja — personalize aqui.
const LOJA = {
  nome: "DM81 Consultoria & Finanças",
  slogan: "Comprar ou vender? Está no lugar certo!",
  cidade: "Vitória da Conquista - BA",
  endereco: "Av. dos Veículos, 1000 - Centro",
  telefone: "(77) 98846-8505",
  // Somente números, com DDI 55 — usado nos links de WhatsApp.
  whatsapp: "5577988468505",
  email: "pointermelo@gmail.com",
  horario: "Seg a Sex: 8h às 18h | Sáb: 8h às 13h",
};
